apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-editor-deployment
  labels:
    app: text-editor
spec:
  replicas: 2 # You can adjust the replica count as needed
  selector:
    matchLabels:
      app: text-editor
  template:
    metadata:
      labels:
        app: text-editor
    spec:
      containers:
      - name: text-editor-container
        image: harshitshubham/text-editor:build-19
        ports:
        - containerPort: 5000
        
---
apiVersion: v1
kind: Service
metadata:
  name: text-editor-service
  labels:
    app: text-editor
spec:
  selector:
    app: text-editor
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer # Change to NodePort if not using a cloud provider
